name: Deploy to GitHub Pages

on:
  schedule:
    - cron: '0 2 * * *'  # Every day at 2:00 UTC
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install
          node script.js
        env:
          ACCESS_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Build static site
        run: |
          npm run build
          touch build/.nojekyll

      - name: Auto-commit new blog files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update blog data [auto-commit]"
          file_pattern: "data/blog"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
          force_orphan: true
